### PR TITLE
add Bitauth IDE, Chaingraph, and Libauth

### PR DESCRIPTION
**Pull request by bitjson**

### CODE REVIEW

**Comment by dsmurrell** [comment]
Thanks Json! ;P

**Comment by bitjson** [comment]
Thank you!

**Comment by dsmurrell** [comment]
chaingraph looks great! not come across this before, is it new?

**Comment by bitjson** [comment]
[Announced Nov 11](https://twitter.com/bitjson/status/1458827747351015430)!

**Pull request merged**
