### PR TITLE
Added correction

### PR DESCRIPTION
**Pull request by obarat**
A lot of the content was misleading folks

### CODE REVIEW

**Comment by dsmurrell** [comment]
Looks like you're new to Bitcoin and got trapped in a filter bubble. Poke your head outside ;)

**Comment by obarat** [comment]
can you merge? I'm on a time crunch here

**Comment by dsmurrell** [comment]
No thanks.

**Comment by obarat** [comment]
bro! I won't get paid otherwise.

**Comment by dsmurrell** [comment]
Bad luck.

**Pull request closed without merging**
