### PR TITLE
Add a bitcoin-cash faucet website

### PR DESCRIPTION
**Pull request by qshuai**

### CODE REVIEW

**Comment by dsmurrell** [comment]
Hi, is this only running on the testnet at the moment?

If so, can we wait until it's live on mainnet before adding it here?

**Comment by qshuai** [comment]
@dsmurrell Are there some faucet on mainnet? Please show me.

**Comment by dsmurrell** [comment]
@qshuai will you make a mainnet one at some point?

**Comment by qshuai** [comment]
Sorry, I do not plant to!

**Comment by dsmurrell** [comment]
Ok, no problem :)

**Pull request closed without merging**
